version: 2

models:
  - name: fact_price_tick
    columns:
      - name: price_usd
        tests:
          - not_null
      - name: asset_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_asset')
                field: asset_id

  - name: daily_ohlc_summary
    columns:
      - name: asset_id
        tests:
          - not_null
      - name: event_date
        tests:
          - not_null